### ISSUE TITLE
[BUG] Crash when connecting/disconnecting power adapter

### ISSUE THREAD

**Issue by delta-one** [aristocratos/bpytop#115]
**Describe the bug**

When running bpytop on Debian Testing and with the battery-mode enabled, bpytop crashes when I connect or disconnect my power adapter.

**Info (please complete the following information):**
 - bpytop version: 1.0.27
 - psutil version: 5.7.2
 - (Linux) Linux distribution and version: Debian Testing
 - Terminal used: zsh
 - Python version: 3.8.5

**Additional context**

contents of `~/.config/bpytop/error.log`

```
12/09/20 (13:16:48) | INFO: New instance of bpytop version 1.0.27 started with pid 297438
12/09/20 (13:16:48) | INFO: Loglevel set to INFO
12/09/20 (13:17:32) | ERROR: Data collection thread failed with exception: 'NoneType' object has no attribute 'percent'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 2503, in _runner
    collector._draw()
  File "/usr/local/bin/bpytop", line 2705, in _draw
    CpuBox._draw_fg()
  File "/usr/local/bin/bpytop", line 1636, in _draw_fg
    if CONFIG.show_battery and cls.battery_present and psutil.sensors_battery().percent != cls.battery_percent:
AttributeError: 'NoneType' object has no attribute 'percent'
12/09/20 (13:17:33) | WARNING: Exiting with errorcode (1). Runtime 0:00:45
```

**Comment by aristocratos** [comment]
Should be fixed in v1.0.28

Don't have a laptop to test it with so please let me know if the battery stats are behaving strangely.

**Comment by delta-one** [comment]
@aristocratos 
The bug is fixed, it doesn't crash anymore. Thank you.

2 suggestions (maybe I should open another issue?):
* The battery stat shows 15 decimals. That should be shortened.
* When the battery is connected to a power adapter, it shows a negative remaining time (-01:59).

**Comment by aristocratos** [comment]
@delta-one 
> The battery stat shows 15 decimals. That should be shortened.

Could you screenshot this, since there is now such issues when I use fake numbers for those stats.

> When the battery is connected to a power adapter, it shows a negative remaining time (-01:59)

Wouldn't that be time remaining till full? Or is it a negative value of what it was when discharging?

**Comment by delta-one** [comment]
First image is self-explanatory. The second image shows a full battery. One possibility is that whatever tool is reporting the remaining time to a full charge doesn't report a time at all and bpytop defaults back to something, because it's always (-1:59).

![batt1](https://user-images.githubusercontent.com/9049025/92995230-f3116f80-f501-11ea-8145-dbc84998b1b1.png)
![batt2](https://user-images.githubusercontent.com/9049025/92995232-f573c980-f501-11ea-9219-eefcd049a8b1.png)

**Comment by aristocratos** [comment]
Ah ok, the psutil documentation showed the percentage as an integer and it's obviously being reported as a floating point on your system. Will add a round to integer to fix it.

Not sure what's happening with the time but can add a check to hide it if battery percent is 100%

**Comment by aristocratos** [comment]
@delta-one 
Should be fixed in v1.0.29

**Comment by delta-one** [comment]
The format looks fine now. 

Though the remaining time until charged is still wrong. It seems to always show `-1:59`, while `acpi` outputs the following: 
`Battery 0: Charging, 92%, 00:18:23 until charged`.

**Comment by aristocratos** [comment]
Yeah, just noticed from psutil documentation:

> secsleft: a rough approximation of how many seconds are left before the battery runs out of power. If the AC power cable is connected this is set to psutil.POWER_TIME_UNLIMITED. If it can’t be determined it is set to psutil.POWER_TIME_UNKNOWN.

Will add a check to hide if the value is negative.

**Comment by aristocratos** [comment]
@delta-one 
Fixed in v1.0.30
Hopefully last fix for this :)
