### ISSUE TITLE
[BUG] Individual core temperatures do not match labelled core and CPU Temperature appears wrong.

### ISSUE THREAD

**Issue by 88mm** [aristocratos/bpytop#156]
**Describe the bug**

Individual core temperatures do not match labelled core and CPU Temperature appears wrong.

**To Reproduce**

Launch bpytop-1.0.44. on lightly loaded system.
Run a single-threaded program that is CPU bound (ie. 100% CPU usage of a thread.)
Observe that the temperature for core showing 100% usage is not the "hot" core.
   Also, CPU temperature does not change with  load. (I did try cycling through the CPU sensors options within bpytop, this did not help.)

**Expected behavior**

The one core that is running at 100% should be the "hot" core.
Also I think the CPU temperature should be the CPU Package temperature.

**Screenshots**

bpytop-screen.png:  bpytop running with Core 2  at 100% showing temperature of 35C.
  It also shows Core 24 having a temperature of 57C, the "hot" core.
![bpytop-screen](https://user-images.githubusercontent.com/73148245/96777543-4d261000-139f-11eb-9273-7d1f4a69c71d.png)

bpytop-sensors.png: partial output of lm-sensors showing Core 1 as the "hot" core, as it should.  (Note lm-sensors starts numbering cores at zero instead of one like bpytop.  https://github.com/lm-sensors/lm-sensors)  Also the package temperature from lm-sensors is what the CPU temperature from bpytop should show, I think.  Finally lm-sensors shows each core not each thread.
![bpytop-sensors](https://user-images.githubusercontent.com/73148245/96778365-75fad500-13a0-11eb-9367-4cfd78b00844.png)

bpytop-i7z.png: screen shot of i7z showing Core 2 as the core with about 100% load like bpytop and also showing it as the "hot" core.  Like lm-sensors i7z only shows each core not each thread like bpytop.  https://github.com/ajaiantilal/i7z
![bpytop-i7z](https://user-images.githubusercontent.com/73148245/96780601-a8f19880-13a1-11eb-8f0e-206ec3bdf3e1.png)

**Info (please complete the following information):**
 - bpytop version:  1.0.44
 - psutil version: 5.7.0-r1
 - (Linux) Linux distribution and version: Gentoo Base System release 2.7
 - (OSX/FreeBSD) Os release version: NA
 - Terminal used:  xterm  v. 351
 - Font used: terminus
 - Python version, `python3 --version` (version 3.6 or above is required): 3.7.9

**Additional context**

CPU:  Intel(R) Core(TM) i9-7940X CPU @ 3.10GHz

contents of `~/.config/bpytop/error.log`    This is a zero length file on my system even after running with --debug.

(try running bpytop with `--debug` flag if error.log is empty)

**Comment by aristocratos** [comment]
@88mm 
Would you mind running `python3 -c "import psutil; print(psutil.sensors_temperatures())"` and posting the output.
Need to see if there is any sensor labels that's conflicting with the temp sensor labels.

**Comment by 88mm** [comment]
$ python3 -c "import psutil; print(psutil.sensors_temperatures())"
{'nct6792': [shwtemp(label='SYSTIN', current=37.0, high=85.0, critical=85.0), shwtemp(label='PCH_CPU_TEMP', current=0.0, high=None, critical=None), shwtemp(label='CPUTIN', current=34.0, high=95.0, critical=95.0), shwtemp(label='AUXTIN0', current=10.0, high=None, critical=None), shwtemp(label='AUXTIN1', current=15.0, high=None, critical=None), shwtemp(label='AUXTIN2', current=31.0, high=None, critical=None), shwtemp(label='AUXTIN3', current=25.0, high=None, critical=None), shwtemp(label='PECI Agent 0', current=26.5, high=95.0, critical=100.0), shwtemp(label='PCH_CHIP_CPU_MAX_TEMP', current=35.0, high=None, critical=None), shwtemp(label='PCH_CHIP_TEMP', current=0.0, high=None, critical=None)], 'eno1': [shwtemp(label='PHY Temperature', current=49.296, high=None, critical=None)], 'coretemp': [shwtemp(label='Package id 0', current=36.0, high=100.0, critical=110.0), shwtemp(label='Core 8', current=35.0, high=100.0, critical=110.0), shwtemp(label='Core 9', current=33.0, high=100.0, critical=110.0), shwtemp(label='Core 10', current=32.0, high=100.0, critical=110.0), shwtemp(label='Core 11', current=34.0, high=100.0, critical=110.0), shwtemp(label='Core 12', current=33.0, high=100.0, critical=110.0), shwtemp(label='Core 13', current=35.0, high=100.0, critical=110.0), shwtemp(label='Core 14', current=33.0, high=100.0, critical=110.0), shwtemp(label='Core 0', current=36.0, high=100.0, critical=110.0), shwtemp(label='Core 1', current=33.0, high=100.0, critical=110.0), shwtemp(label='Core 2', current=33.0, high=100.0, critical=110.0), shwtemp(label='Core 3', current=32.0, high=100.0, critical=110.0), shwtemp(label='Core 4', current=35.0, high=100.0, critical=110.0), shwtemp(label='Core 5', current=32.0, high=100.0, critical=110.0), shwtemp(label='Core 6', current=33.0, high=100.0, critical=110.0), shwtemp(label='Package id 0', current=36.0, high=100.0, critical=110.0), shwtemp(label='Core 8', current=35.0, high=100.0, critical=110.0), shwtemp(label='Core 9', current=33.0, high=100.0, critical=110.0), shwtemp(label='Core 10', current=32.0, high=100.0, critical=110.0), shwtemp(label='Core 11', current=34.0, high=100.0, critical=110.0), shwtemp(label='Core 12', current=33.0, high=100.0, critical=110.0), shwtemp(label='Core 13', current=35.0, high=100.0, critical=110.0), shwtemp(label='Core 14', current=33.0, high=100.0, critical=110.0), shwtemp(label='Core 0', current=36.0, high=100.0, critical=110.0), shwtemp(label='Core 1', current=33.0, high=100.0, critical=110.0), shwtemp(label='Core 2', current=33.0, high=100.0, critical=110.0), shwtemp(label='Core 3', current=32.0, high=100.0, critical=110.0), shwtemp(label='Core 4', current=35.0, high=100.0, critical=110.0), shwtemp(label='Core 5', current=32.0, high=100.0, critical=110.0), shwtemp(label='Core 6', current=33.0, high=100.0, critical=110.0)]}

**Comment by 88mm** [comment]
Better formatting from ipython:

{'nct6792': [shwtemp(label='SYSTIN', current=37.0, high=85.0, critical=85.0),
  shwtemp(label='PCH_CPU_TEMP', current=0.0, high=None, critical=None),
  shwtemp(label='CPUTIN', current=34.0, high=95.0, critical=95.0),
  shwtemp(label='AUXTIN0', current=10.0, high=None, critical=None),
  shwtemp(label='AUXTIN1', current=15.0, high=None, critical=None),
  shwtemp(label='AUXTIN2', current=31.0, high=None, critical=None),
  shwtemp(label='AUXTIN3', current=25.0, high=None, critical=None),
  shwtemp(label='PECI Agent 0', current=26.0, high=95.0, critical=100.0),
  shwtemp(label='PCH_CHIP_CPU_MAX_TEMP', current=35.0, high=None, critical=None),
  shwtemp(label='PCH_CHIP_TEMP', current=0.0, high=None, critical=None)],
 'eno1': [shwtemp(label='PHY Temperature', current=50.933, high=None, critical=None)],
 'coretemp': [shwtemp(label='Package id 0', current=35.0, high=100.0, critical=110.0),
  shwtemp(label='Core 8', current=34.0, high=100.0, critical=110.0),
  shwtemp(label='Core 9', current=34.0, high=100.0, critical=110.0),
  shwtemp(label='Core 10', current=32.0, high=100.0, critical=110.0),
  shwtemp(label='Core 11', current=34.0, high=100.0, critical=110.0),
  shwtemp(label='Core 12', current=32.0, high=100.0, critical=110.0),
  shwtemp(label='Core 13', current=34.0, high=100.0, critical=110.0),
  shwtemp(label='Core 14', current=32.0, high=100.0, critical=110.0),
  shwtemp(label='Core 0', current=35.0, high=100.0, critical=110.0),
  shwtemp(label='Core 1', current=33.0, high=100.0, critical=110.0),
  shwtemp(label='Core 2', current=33.0, high=100.0, critical=110.0),
  shwtemp(label='Core 3', current=32.0, high=100.0, critical=110.0),
  shwtemp(label='Core 4', current=33.0, high=100.0, critical=110.0),
  shwtemp(label='Core 5', current=32.0, high=100.0, critical=110.0),
  shwtemp(label='Core 6', current=33.0, high=100.0, critical=110.0),
  shwtemp(label='Package id 0', current=35.0, high=100.0, critical=110.0),
  shwtemp(label='Core 8', current=34.0, high=100.0, critical=110.0),
  shwtemp(label='Core 9', current=34.0, high=100.0, critical=110.0),
  shwtemp(label='Core 10', current=32.0, high=100.0, critical=110.0),
  shwtemp(label='Core 11', current=34.0, high=100.0, critical=110.0),
  shwtemp(label='Core 12', current=32.0, high=100.0, critical=110.0),
  shwtemp(label='Core 13', current=34.0, high=100.0, critical=110.0),
  shwtemp(label='Core 14', current=32.0, high=100.0, critical=110.0),
  shwtemp(label='Core 0', current=35.0, high=100.0, critical=110.0),
  shwtemp(label='Core 1', current=33.0, high=100.0, critical=110.0),
  shwtemp(label='Core 2', current=33.0, high=100.0, critical=110.0),
  shwtemp(label='Core 3', current=32.0, high=100.0, critical=110.0),
  shwtemp(label='Core 4', current=33.0, high=100.0, critical=110.0),
  shwtemp(label='Core 5', current=32.0, high=100.0, critical=110.0),
  shwtemp(label='Core 6', current=33.0, high=100.0, critical=110.0)]}

**Comment by aristocratos** [comment]
@88mm 
I think the problem is that the Core sensors doesn't list in the correct order. And right now bpytop just maps the sensors without checking for numbering (this is the first time I've seen them not ordered correctly).

I'm gonna be rewriting part of cpu temp function for the current Ryzen issue so will take a look at creating some proper mapping for Intel as well then.

Will have some time this weekend to work on both these issues.

**Comment by aristocratos** [comment]
@88mm 
Should be fixed in v1.0.45

**Comment by 88mm** [comment]
I am now using bpytop-1.0.45 via zip download from github.com.  Unfortunately, this issue persists.  See bpytop-screen4.png.  C2 is at 100% load and all other cores are < 25%.  The "hot" core is C24. (I did not 'rm -r ~/.config/bpytop' before the update.)
![bpytop-screen4](https://user-images.githubusercontent.com/73148245/97097293-37794a80-162c-11eb-8941-9cd3f70ddf70.png)

**Comment by aristocratos** [comment]
@88mm 
Would you mind comparing `python3 -c "import psutil; print(psutil.sensors_temperatures())"` with `i7z` too see if the correct core id and temp is the same in psutil as in i7z.

Also could you post the output of `/proc/cpuinfo` from your system.

**Comment by 88mm** [comment]
Here is processor 0 from 'cat /proc/cpuinfo'   I'll post the other 27 entries if you want but they seem similar:

    processor       : 0
    vendor_id       : GenuineIntel
    cpu family      : 6
    model           : 85
    model name      : Intel(R) Core(TM) i9-7940X CPU @ 3.10GHz
    stepping        : 4
    microcode       : 0x200004d
    cpu MHz         : 1332.679
    cache size      : 19712 KB
    physical id     : 0
    siblings        : 28
    core id         : 0
    cpu cores       : 14
    apicid          : 0
    initial apicid  : 0
    fpu             : yes
    fpu_exception   : yes
    cpuid level     : 22
    wp              : yes
    flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts flush_l1d
    vmx flags       : vnmi preemption_timer posted_intr invvpid ept_x_only ept_ad ept_1gb flexpriority apicv tsc_offset vtpr mtf vapic ept vpid unrestricted_guest vapic_reg vid ple ept_mode_based_exec tsc_scaling
    bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
    bogomips        : 6202.33
    clflush size    : 64
    cache_alignment : 64
    address sizes   : 46 bits physical, 48 bits virtual
    power management:

=============

There was nothing in my error.log file so I set it to debug and restarted bpytop and now have this:

     ~/.config/bpytop]$ cat error.log 
    25/10/20 (09:34:13) | INFO: Loglevel set to INFO
    25/10/20 (09:34:15) | INFO: Loglevel set to DEBUG
    25/10/20 (09:34:17) | INFO: Loglevel set to INFO
    25/10/20 (09:34:18) | INFO: Loglevel set to DEBUG
    25/10/20 (09:36:00) | INFO: Exiting. Runtime 0:50:38 
    
    25/10/20 (09:36:09) | INFO: New instance of bpytop version 1.0.45 started with pid 26162
    25/10/20 (09:36:09) | INFO: Loglevel set to DEBUG
    25/10/20 (09:36:09) | DEBUG: Using psutil version 5.7.0
    25/10/20 (09:36:09) | DEBUG: CMD: ./bpytop.py
    25/10/20 (09:36:11) | DEBUG: Collect and draw completed in 0.562958 seconds
    25/10/20 (09:36:12) | DEBUG: Init completed in 2.932744 seconds

=======

I'll compare the python psutil and i7z in the next post.

**Comment by aristocratos** [comment]
@88mm 
`grep 'processor\|core id' /proc/cpuinfo` would do it, that's the information bpytop uses for mapping the cpu core to the coretemp.

**Comment by 88mm** [comment]
Here are two runs of one single threaded python app running at 100%.  For each run I show  a screenshot of bpytop and i7z followed by the text output of python's psutil.sensors_temperatures().

Run 1   C6 has the load and bpytop shows threads C14 & C28 as the "hot" core. (I understand that because I have 14-cores + hyperthreading that pairs of the CPUs 28 threads will have the same temperature.)

![bpytop](https://user-images.githubusercontent.com/73148245/97114468-e0b45500-16ad-11eb-8ec5-b6771f61adbe.png)

i7z for run 1
![bpytop_i7z](https://user-images.githubusercontent.com/73148245/97114548-5f10f700-16ae-11eb-9e9e-aeb0f20f8650.png)

Python's psutil.sensors_temperatures() for run 1.  Note the "hot" core is core 5 here.  (Perhaps the one-off is the difference between the core number and the core-id number? )

    In [4]: psutil.sensors_temperatures()
    Out[4]: 
    {'nct6792': [shwtemp(label='SYSTIN', current=35.0, high=85.0, critical=85.0),
    shwtemp(label='PCH_CPU_TEMP', current=0.0, high=None, critical=None),
    shwtemp(label='CPUTIN', current=33.0, high=95.0, critical=95.0),
    shwtemp(label='AUXTIN0', current=10.0, high=None, critical=None),
    shwtemp(label='AUXTIN1', current=15.0, high=None, critical=None),
    shwtemp(label='AUXTIN2', current=30.0, high=None, critical=None),
    shwtemp(label='AUXTIN3', current=25.0, high=None, critical=None),
    shwtemp(label='PECI Agent 0', current=45.0, high=95.0, critical=100.0),
    shwtemp(label='PCH_CHIP_CPU_MAX_TEMP', current=33.0, high=None, critical=None),
    shwtemp(label='PCH_CHIP_TEMP', current=0.0, high=None, critical=None)],
    'eno1': [shwtemp(label='PHY Temperature', current=49.539, high=None, critical=None)],
    'coretemp': [shwtemp(label='Package id 0', current=55.0, high=100.0, critical=110.0),
    shwtemp(label='Core 8', current=34.0, high=100.0, critical=110.0),
    shwtemp(label='Core 9', current=33.0, high=100.0, critical=110.0),
    shwtemp(label='Core 10', current=34.0, high=100.0, critical=110.0),
    shwtemp(label='Core 11', current=34.0, high=100.0, critical=110.0),
    shwtemp(label='Core 12', current=36.0, high=100.0, critical=110.0),
    shwtemp(label='Core 13', current=35.0, high=100.0, critical=110.0),
    shwtemp(label='Core 14', current=35.0, high=100.0, critical=110.0),
    shwtemp(label='Core 0', current=35.0, high=100.0, critical=110.0),
    shwtemp(label='Core 1', current=33.0, high=100.0, critical=110.0),
    shwtemp(label='Core 2', current=33.0, high=100.0, critical=110.0),
    shwtemp(label='Core 3', current=35.0, high=100.0, critical=110.0),
    shwtemp(label='Core 4', current=34.0, high=100.0, critical=110.0),
    shwtemp(label='Core 5', current=56.0, high=100.0, critical=110.0),
    shwtemp(label='Core 6', current=38.0, high=100.0, critical=110.0),
    shwtemp(label='Package id 0', current=55.0, high=100.0, critical=110.0),
    shwtemp(label='Core 8', current=34.0, high=100.0, critical=110.0),
    shwtemp(label='Core 9', current=33.0, high=100.0, critical=110.0),
    shwtemp(label='Core 10', current=34.0, high=100.0, critical=110.0),
    shwtemp(label='Core 11', current=34.0, high=100.0, critical=110.0),
    shwtemp(label='Core 12', current=36.0, high=100.0, critical=110.0),
    shwtemp(label='Core 13', current=35.0, high=100.0, critical=110.0),
    shwtemp(label='Core 14', current=35.0, high=100.0, critical=110.0),
    shwtemp(label='Core 0', current=35.0, high=100.0, critical=110.0),
    shwtemp(label='Core 1', current=33.0, high=100.0, critical=110.0),
    shwtemp(label='Core 2', current=33.0, high=100.0, critical=110.0),
    shwtemp(label='Core 3', current=35.0, high=100.0, critical=110.0),
    shwtemp(label='Core 4', current=34.0, high=100.0, critical=110.0),
    shwtemp(label='Core 5', current=56.0, high=100.0, critical=110.0),
    shwtemp(label='Core 6', current=38.0, high=100.0, critical=110.0)]}

====================

Here is run 2.  C11 shows the 100% CPU load and threads C5 & C19 show the "hot" core.

![bpytop2](https://user-images.githubusercontent.com/73148245/97114817-05113100-16b0-11eb-913d-2389d2d1ae8c.png)

The i7z screen shot also shows C11 as having the load and "hot" temp.

![bpytop_i7z2](https://user-images.githubusercontent.com/73148245/97115043-7f8e8080-16b1-11eb-968b-e18d70961bd5.png)

Finally here is run2's python psutil.sensors_temperatures().  This time AGREEING that the loaded core/thread is hot.

    In [8]: psutil.sensors_temperatures()
    Out[8]: 
    {'nct6792': [shwtemp(label='SYSTIN', current=34.0, high=85.0, critical=85.0),
    shwtemp(label='PCH_CPU_TEMP', current=0.0, high=None, critical=None),
    shwtemp(label='CPUTIN', current=32.0, high=95.0, critical=95.0),
    shwtemp(label='AUXTIN0', current=10.0, high=None, critical=None),
    shwtemp(label='AUXTIN1', current=15.0, high=None, critical=None),
    shwtemp(label='AUXTIN2', current=29.0, high=None, critical=None),
    shwtemp(label='AUXTIN3', current=25.0, high=None, critical=None),
    shwtemp(label='PECI Agent 0', current=37.0, high=95.0, critical=100.0),
    shwtemp(label='PCH_CHIP_CPU_MAX_TEMP', current=32.0, high=None, critical=None),
    shwtemp(label='PCH_CHIP_TEMP', current=0.0, high=None, critical=None)],
    'eno1': [shwtemp(label='PHY Temperature', current=46.019, high=None, critical=None)],
    'coretemp': [shwtemp(label='Package id 0', current=47.0, high=100.0, critical=110.0),
    shwtemp(label='Core 8', current=34.0, high=100.0, critical=110.0),
    shwtemp(label='Core 9', current=33.0, high=100.0, critical=110.0),
    shwtemp(label='Core 10', current=32.0, high=100.0, critical=110.0),
    shwtemp(label='Core 11', current=47.0, high=100.0, critical=110.0),
    shwtemp(label='Core 12', current=33.0, high=100.0, critical=110.0),
    shwtemp(label='Core 13', current=34.0, high=100.0, critical=110.0),
    shwtemp(label='Core 14', current=32.0, high=100.0, critical=110.0),
    shwtemp(label='Core 0', current=35.0, high=100.0, critical=110.0),
    shwtemp(label='Core 1', current=32.0, high=100.0, critical=110.0),
    shwtemp(label='Core 2', current=33.0, high=100.0, critical=110.0),
    shwtemp(label='Core 3', current=32.0, high=100.0, critical=110.0),
    shwtemp(label='Core 4', current=34.0, high=100.0, critical=110.0),
    shwtemp(label='Core 5', current=38.0, high=100.0, critical=110.0),
    shwtemp(label='Core 6', current=33.0, high=100.0, critical=110.0),
    shwtemp(label='Package id 0', current=47.0, high=100.0, critical=110.0),
    shwtemp(label='Core 8', current=34.0, high=100.0, critical=110.0),
    shwtemp(label='Core 9', current=33.0, high=100.0, critical=110.0),
    shwtemp(label='Core 10', current=32.0, high=100.0, critical=110.0),
    shwtemp(label='Core 11', current=47.0, high=100.0, critical=110.0),
    shwtemp(label='Core 12', current=33.0, high=100.0, critical=110.0),
    shwtemp(label='Core 13', current=34.0, high=100.0, critical=110.0),
    shwtemp(label='Core 14', current=32.0, high=100.0, critical=110.0),
    shwtemp(label='Core 0', current=35.0, high=100.0, critical=110.0),
    shwtemp(label='Core 1', current=32.0, high=100.0, critical=110.0),
    shwtemp(label='Core 2', current=33.0, high=100.0, critical=110.0),
    shwtemp(label='Core 3', current=32.0, high=100.0, critical=110.0),
    shwtemp(label='Core 4', current=34.0, high=100.0, critical=110.0),
    shwtemp(label='Core 5', current=38.0, high=100.0, critical=110.0),
    shwtemp(label='Core 6', current=33.0, high=100.0, critical=110.0)]}

**Comment by 88mm** [comment]
grep 'processor\|core id' /proc/cpuinfo
    processor       : 0
    core id         : 0
    processor       : 1
    core id         : 1
    processor       : 2
    core id         : 2
    processor       : 3
    core id         : 3
    processor       : 4
    core id         : 4
    processor       : 5
    core id         : 5
    processor       : 6
    core id         : 6
    processor       : 7
    core id         : 8
    processor       : 8
    core id         : 9
    processor       : 9
    core id         : 10
    processor       : 10
    core id         : 11
    processor       : 11
    core id         : 12
    processor       : 12
    core id         : 13
    processor       : 13
    core id         : 14
    processor       : 14
    core id         : 0
    processor       : 15
    core id         : 1
    processor       : 16
    core id         : 2
    processor       : 17
    core id         : 3
    processor       : 18
    core id         : 4
    processor       : 19
    core id         : 5
    processor       : 20
    core id         : 6
    processor       : 21
    core id         : 8
    processor       : 22
    core id         : 9
    processor       : 23
    core id         : 10
    processor       : 24
    core id         : 11
    processor       : 25
    core id         : 12
    processor       : 26
    core id         : 13
    processor       : 27
    core id         : 14

**Comment by aristocratos** [comment]
@88mm 
There is something weird going on in your `/proc/cpuinfo`
Look a "processor 7", it suddently jumps 1 in the core id numbering. There doesn't seem to be a "core id 7".
I think it's messing up the mapping and I have no clue why I looks like that.

**Comment by aristocratos** [comment]
Although, there is neither a "Core 7" in the psutil coretemps...

**Comment by aristocratos** [comment]
@88mm 
I found the cause of the problem. Sensor "CPUTIN" got picked before "Package id 0" and bpytop threw away the core mapping because it assumed it wasn't an Intel cpu. Will be fixed shortly.

**Comment by 88mm** [comment]
Thanks.  (I was starting to look at sibling lists:  cat /sys/devices/system/cpu/cpu*/topology/thread_siblings_list | sort -n | uniq )

**Comment by aristocratos** [comment]
@88mm
Ok, try out 1.0.46. It's working when emulating your sensors and cpuinfo, so should be good.

**Comment by 88mm** [comment]
Yes, the loaded core and temperatures match.  Also the overall CPU temperature now works (both with configuration selecting "Auto" and "package id".  I did not try the rest.)

Thanks for a very useful system monitoring tool that looks really good too.  (Guess I can retire htop.)
I look forward to seeing the results of a  couple of the TODO items in the bpytop readme:  GPU monitoring and box resizing.

**Comment by aristocratos** [comment]
No problem :)
GPU monitoring will probably be a while, waiting on a rtx 3080 and it's not looking very hopeful at the moment :(
