### ISSUE TITLE
[BUG] Bpytop doesn't show temps on RPi4

### ISSUE THREAD

**Issue by RedBearAK** [aristocratos/bpytop#45]
Hardware: Raspberry Pi 4B 8GB
Software: Twister OS 1.5 (basically just a skin on top of Raspbian 32-bit)

Bpytop doesn't show CPU temps for me on this platform, which is odd because Bashtop shows the temps just fine on the same machine. Doesn't seem to be a problem with the menu setting. 

Screenshot (Bashtop left, Bpytop right): 

![Screenshot_2020-08-08_16-00-59](https://user-images.githubusercontent.com/64876997/89722198-49374400-d993-11ea-9c86-b2d40103513f.png)

**Comment by RedBearAK** [comment]
I also noticed just now that Bashtop shows its name in the terminal title bar, while Bpytop doesn't. A minor issue, but it can be handy when Alt+Tabbing between many open terminal windows.

**Comment by RedBearAK** [comment]
Notice there is a mysterious "e" off by itself in the Bpytop screenshot. That disappears when I set "Check temp" to false. So maybe it's just some kind of screen rendering issue. Like the temps are being covered up by the rest of the CPU info box.

**Comment by aristocratos** [comment]
Fixed in v1.0.8

**Comment by RedBearAK** [comment]
Celebrated too soon. Regret to report mission failure, Captain. 

The phantom "e" has certainly disappeared, but the temp block doesn't show even after cycling the "Check temp" option True-False-True. This time there is no visible difference regardless of the setting. 

Still working fine in bashtop. Let me know if there is something I can do to help troubleshoot, like running a debug version. 

Screenshot: 
![Screen Shot 2020-08-09 at 2 15 40 PM](https://user-images.githubusercontent.com/64876997/89742952-1d779500-da4b-11ea-8243-47c4dc3f129f.png)

**Comment by RedBearAK** [comment]
Neofetch output just in case there's a clue to why it isn't working: 

![Screen Shot 2020-08-09 at 2 26 59 PM](https://user-images.githubusercontent.com/64876997/89743146-988d7b00-da4c-11ea-8d02-6ce0f8648d08.png)

**Comment by RedBearAK** [comment]
Just noticed the name is back in the title bar already in BpyTOP. Nice.

**Comment by aristocratos** [comment]
@RedBearAK 
New attempt: Fixed in v1.0.9 :)

**Comment by drazil100** [comment]
![Screenshot from 2020-08-10 14-12-04](https://user-images.githubusercontent.com/17794391/89820998-7c084600-db13-11ea-8e16-391bb405b80a.png)
No temps on my pi on v1.0.9

**Comment by aristocratos** [comment]
@drazil100 

Can you run commands:
`vcgencmd measure_temp`
and
`python3 -c "import subprocess; print(round(float(subprocess.check_output(['vcgencmd', 'measure_temp'], text=True)[5:-2])))"`
on your pi.

**Comment by drazil100** [comment]
```
austin@coded-dragon:~$ sudo vcgencmd measure_temp
temp=33.0'C
austin@coded-dragon:~$ sudo python3 -c "import subprocess; print(round(float(subprocess.check_output(['vcgencmd', 'measure_temp'], text=True)[5:-2])))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: could not convert string to float: "33.0'"
austin@coded-dragon:~$ 
```

**Comment by aristocratos** [comment]
Forgot a newline at the end I think.

try: `python3 -c "import subprocess; print(round(float(subprocess.check_output(['vcgencmd', 'measure_temp'], text=True)[5:-3])))"`

**Comment by aristocratos** [comment]
or instead:
`python3 -c "import subprocess; print(round(float(subprocess.check_output(['vcgencmd', 'measure_temp'], text=True).strip()[5:-2])))"`

**Comment by drazil100** [comment]
```
sudo python3 -c "import subprocess; print(round(float(subprocess.check_output(['vcgencmd', 'measure_temp'], text=True).strip()[5:-2])))"
34
```

**Comment by aristocratos** [comment]
Alright, thanks :) Should be fixed in next version.

Always a bother to get these things working when not having the actual hardware to test on.

**Comment by aristocratos** [comment]
Finally fixed in v1.0.10

**Comment by drazil100** [comment]
![Screenshot from 2020-08-10 15-46-04](https://user-images.githubusercontent.com/17794391/89829669-94329200-db20-11ea-8973-c51f2e95192b.png)
![Screenshot from 2020-08-10 15-46-45](https://user-images.githubusercontent.com/17794391/89829712-a6143500-db20-11ea-916b-82869a65b10c.png)

**Comment by RedBearAK** [comment]
I get the same output from those commands as drazil100. 

However, although I'm sure you're fixing something, I still don't see the temps. I've verified I'm using 1.0.10 and "Check temp" is enabled. 

Also this version seems to take an unusually long time to go through the checklist before it starts up. Like around 10 seconds, where previously it seemed more like around 3 seconds at the most.

**Comment by drazil100** [comment]
@RedBearAK The checklist is completely and entirely optional and can be turned off in the options. Loads pretty much instantly when "Show init" is disabled

**Comment by RedBearAK** [comment]
> @RedBearAK The checklist is completely and entirely optional and can be turned off in the options. Loads pretty much instantly when "Show init" is disabled

I did not realize that, thanks. Still odd that it's suddenly taking a lot longer.

**Comment by drazil100** [comment]
I figured out the problem. vcgencmd requires sudo to run. Bashtop has the same issue with pi temperatures but if I run it with sudo it works. Sudo does not however help with bpytop. My friend suggests checking out "/sys/class/thermal/thermal_zone0/temp". He says it works with x86 too.

**Comment by drazil100** [comment]
From my friend:
"I really recommend that he looks into more stuff that he could look up in /proc or /sys without shelling out to subprocess
It'd be a lot lighter
Spinning up processes and pipes is kinda expensive
(that said using /proc for processes would be counterproductive and using psutil like he is is definitely the better approach)"

**Comment by RedBearAK** [comment]
> I figured out the problem. vcgencmd requires sudo to run. Bashtop has the same issue with pi temperatures but if I run it with sudo it works. Sudo does not however help with bpytop. My friend suggests checking out "/sys/class/thermal/thermal_zone0/temp". He says it works with x86 too.

@drazil100 
That doesn't make much sense to me. Neither of the commands from earlier in this thread required sudo to run on my system, and I actually don't understand why you ran them with sudo. I've also never needed to run BashTOP as sudo to see the temps displayed on any Raspberry Pi operating system I've tried. The shell script that I made to display GPU and CPU temps on the RPi4B (copied from some online forum) has never needed sudo to work. I think you're barking up the wrong tree. What OS are you using?

**Comment by drazil100** [comment]
Raspbian. And I ran them with sudo because it returned this when I didn't
```
austin@coded-dragon:~$ vcgencmd measure_temp
VCHI initialization failed
austin@coded-dragon:~$ python3 -c "import subprocess; print(round(float(subprocess.check_output(['vcgencmd', 'measure_temp'], text=True).strip()[5:-2])))"
VCHI initialization failed
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['vcgencmd', 'measure_temp']' returned non-zero exit status 255.
austin@coded-dragon:~$
```

**Comment by elitearmedforce** [comment]
+1. This still doesn't work yet (v1.0.10). I use both Bashtop & Bpytop. You mentioned this command and this works perfectly {sudo python3 -c "import subprocess; print(round(float(subprocess.check_output(['vcgencmd', 'measure_temp'], text=True).strip()[5:-2])))"}

Love your work. Fan of this TUI

**Comment by drazil100** [comment]
@RedBearAK 
Also just cause bashtop doesn't require you to run it as sudo to see temps doesn't mean mine doesn't and i'm on the official distro. Trying to provide as much information as I can is all. :P

**Comment by RedBearAK** [comment]
@drazil100 
That is weird. I don't recall needing to use sudo to run vcgencmd even on stock Raspberry PI OS, but I could be wrong. Perhaps you should think about getting a newer version of the OS. 

I don't feel like it's normal to need to sudo just to check the temps. I can't run something like "apt update" on my system without sudo, but I can run vcgencmd just fine with user permissions. 

Certainly it will need to be addressed if that is actually how Raspbian or current Raspberry PI OS behaves by default, but I think your issue is actually a separate problem from why the temps aren't displaying, at least on my system.

**Comment by drazil100** [comment]
Its possible its because im not using the pi account the image came with. Either way vcgencmd is probably not something that should be permissionless cause it does quite a bit more than just check the temperatures. Also I got my pi is pretty current on the OS.

**Comment by RedBearAK** [comment]
> Its possible its because im not using the pi account the image came with.

@drazil100 
You know, I was going to ask about exactly that. Maybe you're missing one of the permission groups the pi user was in. It's unlikely that it would be worth the trouble for the dev to try and work around not being able to run vcgencmd without sudo, when you could just run bpytop as sudo if you need to, the same way you've been running bashtop to make it show temps.

**Comment by drazil100** [comment]
The problem is bpytop doesn't seem to take that workaround for vcgencmd. Already tried. Thats why I am mentioning it got the CPU temps to show on bashtop and not bpytop. :P

**Comment by RedBearAK** [comment]
I booted up a new image of Raspberry Pi OS (32-bit), did all updates and installed bpytop. Runs, but no temps. The default "pi" user can run vcgencmd without sudo. A new user couldn't. I got that same VCHI error. 

These are the groups the default user is part of: 
pi adm dialout cdrom sudo audio video plugdev games users input netdev gpio i2c spi

At a guess, your user might be missing the "adm" group, which I'm assuming is short for "administrators". If you weren't in the "sudo" group you wouldn't even be able to use sudo at all, theoretically. 

I still don't think this is related to the issue of the temps showing in the Bash version but not showing in the Python port, on the same machine at the same time under the same user.

**Comment by drazil100** [comment]
Maybe but it could be. Ideally it would be best if bpytop didn't need to rely on a program that requires root privileges anyway. even if the default account is in a group that would allow it to be run without them it would be best not to require them. .

**Comment by aristocratos** [comment]
I forgot to change a line in an earlier function that checks if any temperature data is available.
Will be fixed later today.

**Comment by aristocratos** [comment]
Fixed in v1.0.11
Hopefully :)

**Comment by drazil100** [comment]
Yes and no. If I run it with sudo it shows temps but without sudo it does not for me. I have yet to sit down to try adding myself to the same groups as the pi user.

This should fix it for @RedBearAK though :P

**Comment by drazil100** [comment]
@aristocratos Is this the color you would expect it to draw the temps as for the temperature?

![Screenshot from 2020-08-11 14-19-16](https://user-images.githubusercontent.com/17794391/89939486-a6bed100-dbdd-11ea-92fd-7b1e8fa1b365.png)

**Comment by aristocratos** [comment]
> If I run it with sudo it shows temps but without sudo it does not for me.

That's out of my hands. But would be great if I could find a way to get the pi temps without having to rely on a external program. But as far as I know, if they show up at all in psutil.sensors_temperatures() they are usually named something like "temp" which isn't helpful in detecting cpu.

@drazil100 
Would you mind running `python3 -c "import psutil; print(psutil.sensors_temperatures())"` on your pi.

**Comment by drazil100** [comment]
```
austin@coded-dragon:~/Repositories/bpytop$ python3 -c "import psutil; print(psutil.sensors_temperatures())"
{'cpu_thermal': [shwtemp(label='', current=34.076, high=None, critical=None)]}
```

**Comment by aristocratos** [comment]
> Is this the color you would expect it to draw the temps as for the temperature?

Nope, I forgot to set the cpu_temp_high and cpu_temp_crit values manually.

**Comment by aristocratos** [comment]
> cpu_thermal
Huh, that's at least an identifier with "cpu" in it. Would need to confirm with some other people running raspberry pi's though that they get the same name.

**Comment by drazil100** [comment]
Yeah preferably other models too as it might vary based on hardware.  Mine is a Raspberry Pi 4.

**Comment by aristocratos** [comment]
@drazil100 
You don't happen to know if there is a "critical" cpu temperature for raspberry pi's in general?

**Comment by aristocratos** [comment]
I could set the high and critical values to something general like 80 and 95 otherwise.

**Comment by RedBearAK** [comment]
Yes, it does fix it for RedBearAK. 

Whodunit? You dunit, @aristocratos 👍 

I can't really tell because the room the Pi is in is cold at the moment and it has a big Ice Tower cooler with thermal paste, so the stress test is failing to increase the temp, but did you make the color of the temp display responsive to the temperature range? Or is it just changed from solid blue to solid purple? 

![Screen Shot 2020-08-11 at 11 14 01 AM](https://user-images.githubusercontent.com/64876997/89939727-df9e7c00-dbc4-11ea-9fe3-9b6e5ce8a569.png)

![Screen Shot 2020-08-11 at 11 18 43 AM](https://user-images.githubusercontent.com/64876997/89940158-900c8000-dbc5-11ea-8ca2-25fcf921b776.png)

**Comment by aristocratos** [comment]
@RedBearAK 

No it's because:

> 

    Is this the color you would expect it to draw the temps as for the temperature?

> 

> Nope, I forgot to set the cpu_temp_high and cpu_temp_crit values manually.

**Comment by aristocratos** [comment]
Seems like at least the pi 4 soft throttles at 60C and hard throttles at 80C. So might use those values for now.

**Comment by RedBearAK** [comment]
My output running 32-bit Twister OS 1.5.2

```
pi@twisteros:~/Downloads $ python3 -c "import psutil; print(psutil.sensors_temperatures())"
{'cpu_thermal': [shwtemp(label='', current=31.154, high=None, critical=None)]}
```

**Comment by aristocratos** [comment]
Might have to look into the psutil source to investigate if 'cpu_thermal' is something reported from the sensors or a common name used by psutil. If it is, I should be able to get rid of using "vcgencmd".

**Comment by RedBearAK** [comment]
So the temp display in bashtop and bpytop does respond to temp changes by changing color? 

Guess I never really noticed because my cooler is too efficient. I can never get it to go above 40C anymore under a stress test, even when the room is warm. With the thermal pad that came with the cooler the temps would go to 60C.

**Comment by drazil100** [comment]
AHA. Figured it out. The group that lets me run vcgencmd without root is "video". Still would be best if temps could be obtained by something that isn't permission locked but now I know what group I need to be in.

**Comment by aristocratos** [comment]
Fixed color range in v1.0.12

**Comment by drazil100** [comment]
Color range works! Thanks!

**Comment by RedBearAK** [comment]
> Fixed color range in v1.0.12

@aristocratos 
Nice work. 
Want me to close the thread since the main issue seems to be solved? 

> AHA. Figured it out. The group that lets me run vcgencmd without root is "video". Still would be best if temps could be obtained by something that isn't permission locked but now I know what group I need to be in.

That totally figures since what vcgencmd is actually reporting is the GPU temp, isn't it?

**Comment by drazil100** [comment]
I have no clue actually.

**Comment by aristocratos** [comment]
Wouldn't it be the temperate for the whole SoC that's reported if it's just 1 value?

I know Pine64 reports multiple SoC values, but they are named CPU and GPU so pretty telling what's what.

**Comment by aristocratos** [comment]
> Want me to close the thread since the main issue seems to be solved?

Yeah, let's close it for now. And just reopen if new related bugs surface.

**Comment by drazil100** [comment]
I know that vcgencmd is how I was told to check temperatures on the pi

**Comment by aristocratos** [comment]
I would guess that `vcgencmd measure_temp` is just converting the value from `/sys/class/thermal/thermal_zone0/temp`.

**Comment by RedBearAK** [comment]
Hey, I've been noticing on a couple of machines that bpytop seems to have some issues updating reliably at times. Almost as if it's getting "stuck" from time to time, especially when the CPU is very busy, but sometimes even when it isn't. For instance, here is bashtop and bpytop side by side, both set to update every 2000ms and both have been running since I started stress-ng, but as you can see the graphs are different. 

![Screen Shot 2020-08-11 at 11 47 05 AM](https://user-images.githubusercontent.com/64876997/89942428-0363c100-dbc9-11ea-9c55-7393da9a0e38.png)

**Comment by aristocratos** [comment]
The graphs on bpytop have double the horizontal resolution that the default on bashtop has. (Two values for each character)
If you enable "hires graphs" in bashtop they should look the same, but bashtops cpu consumption increases to almost double with that option on.

**Comment by drazil100** [comment]
> I would guess that `vcgencmd measure_temp` is just converting the value from `/sys/class/thermal/thermal_zone0/temp`.

Out of curiosity is there a reason you can't use that?

@RedBearAK that should probably be its own issue since its not strictly related to the pi and is definitely not about temperatures.

**Comment by aristocratos** [comment]
> Out of curiosity is there a reason you can't use that?

Would have to know for sure that it is a raspberry pi, otherwise that value could be anything. It's likely that that is the value psutil picks up as "cpu_thermal".

**Comment by RedBearAK** [comment]
The script I copied from a forum somewhere uses both `vcgencmd` and `/sys/class/thermal/thermal_zone0/temp` and states that it measures both GPU and CPU. It is certainly an SoC, but the cores still separately report their own temps. 

```
#!/bin/bash
# Script: my-pi-temp.sh
# Purpose: Display the ARM CPU and GPU  temperature of Raspberry Pi 2/3 
# Author: Vivek Gite <www.cyberciti.biz> under GPL v2.x+
# -------------------------------------------------------

cpu=$(</sys/class/thermal/thermal_zone0/temp)

while true
  do
clear
echo "$(date) @ $(hostname)"
echo "-------------------------------------------"
echo "GPU => $(/opt/vc/bin/vcgencmd measure_temp)"
echo "CPU => $((cpu/1000))'C"
sleep 2
done
```

The output is often the same but also often shows a difference of 1-2 degrees. 

```
Tue 11 Aug 2020 11:58:06 AM AKDT @ twisteros
-------------------------------------------
GPU => temp=31.0'C
CPU => 32'C
```

**Comment by aristocratos** [comment]
Huh, could you run `python3 -c "import psutil; print(psutil.sensors_temperatures())"` and `cat /sys/class/thermal/thermal_zone0/temp` a couple of times just to compare if they are the same.

**Comment by RedBearAK** [comment]
> The graphs on bpytop have double the horizontal resolution that the default on bashtop has. (Two values for each character)
> If you enable "hires graphs" in bashtop they should look the same, but bashtops cpu consumption increases to almost double with that option on.

O-I-C

Ah, so that is what "hires graphs" is supposed to do. I never quite figured that out through casual use. Makes sense.

**Comment by aristocratos** [comment]
Could rewrite it so if `vcgencmd` is detected in the system (which should only be on raspberry pi's right?), then it reads from `sys/class/thermal/thermal_zone0/temp`.

**Comment by aristocratos** [comment]
Since now it's possibly reporting gpu temp as cpu...

Gonna take a look at it tomorrow, need some sleep before work :)

**Comment by drazil100** [comment]
My friend says you can find it in "/sys/class/thermal/thermal_zone0/type"

Just checked mine and it says "cpu-thermal"

**Comment by RedBearAK** [comment]
@aristocratos 
Here is the output of a modified (and fixed) script run several times: 

```
Tue 11 Aug 2020 12:14:19 PM AKDT @ twisteros
-------------------------------------------
GPU => temp=33.0'C
CPU => 34'C
UNKNOWN => {'cpu_thermal': [shwtemp(label='', current=34.076, high=None, critical=None)]}
Tue 11 Aug 2020 12:14:21 PM AKDT @ twisteros
-------------------------------------------
GPU => temp=34.0'C
CPU => 34'C
UNKNOWN => {'cpu_thermal': [shwtemp(label='', current=34.076, high=None, critical=None)]}
Tue 11 Aug 2020 12:14:24 PM AKDT @ twisteros
-------------------------------------------
GPU => temp=33.0'C
CPU => 34'C
UNKNOWN => {'cpu_thermal': [shwtemp(label='', current=32.615, high=None, critical=None)]}
Tue 11 Aug 2020 12:14:27 PM AKDT @ twisteros
-------------------------------------------
GPU => temp=33.0'C
CPU => 34'C
UNKNOWN => {'cpu_thermal': [shwtemp(label='', current=33.102, high=None, critical=None)]}
Tue 11 Aug 2020 12:14:30 PM AKDT @ twisteros
-------------------------------------------
GPU => temp=33.0'C
CPU => 34'C
UNKNOWN => {'cpu_thermal': [shwtemp(label='', current=34.076, high=None, critical=None)]}
Tue 11 Aug 2020 12:14:32 PM AKDT @ twisteros
-------------------------------------------
GPU => temp=33.0'C
CPU => 34'C
UNKNOWN => {'cpu_thermal': [shwtemp(label='', current=34.076, high=None, critical=None)]}
Tue 11 Aug 2020 12:14:35 PM AKDT @ twisteros
-------------------------------------------
GPU => temp=33.0'C
CPU => 33'C
UNKNOWN => {'cpu_thermal': [shwtemp(label='', current=34.076, high=None, critical=None)]}
Tue 11 Aug 2020 12:14:37 PM AKDT @ twisteros
-------------------------------------------
GPU => temp=34.0'C
CPU => 33'C
UNKNOWN => {'cpu_thermal': [shwtemp(label='', current=34.563, high=None, critical=None)]}
Tue 11 Aug 2020 12:14:40 PM AKDT @ twisteros
-------------------------------------------
GPU => temp=33.0'C
CPU => 32'C
UNKNOWN => {'cpu_thermal': [shwtemp(label='', current=32.615, high=None, critical=None)]}
Tue 11 Aug 2020 12:14:42 PM AKDT @ twisteros
-------------------------------------------
GPU => temp=33.0'C
CPU => 34'C
UNKNOWN => {'cpu_thermal': [shwtemp(label='', current=34.076, high=None, critical=None)]}
```

Here is the modified (and fixed) script: 

```
#!/bin/bash
# Script: my-pi-temp.sh
# Purpose: Display the ARM CPU and GPU  temperature of Raspberry Pi 2/3 
# Author: Vivek Gite <www.cyberciti.biz> under GPL v2.x+
# -------------------------------------------------------

clear

#cpu=$(</sys/class/thermal/thermal_zone0/temp)
#unknown=$(python3 -c 'import psutil; print(psutil.sensors_temperatures())')

while true
  do
#       clear
        cpu=$(</sys/class/thermal/thermal_zone0/temp)
        unknown=$(python3 -c 'import psutil; print(psutil.sensors_temperatures())')
        echo "$(date) @ $(hostname)"
        echo "-------------------------------------------"
        echo "GPU => $(/opt/vc/bin/vcgencmd measure_temp)"
        echo "CPU => $((cpu/1000))'C"
        echo "UNKNOWN => $unknown"
        sleep 2
done
```

**Comment by RedBearAK** [comment]
So that was weird. As you can see in the screenshots from earlier, both bashtop and bpytop were only showing 3 cores. Rebooted and it's back to normal. Very strange. 

![Screen Shot 2020-08-11 at 2 03 46 PM](https://user-images.githubusercontent.com/64876997/89953514-b2a99380-dbdb-11ea-9d30-07176b225240.png)

**Comment by aristocratos** [comment]
Added collection through psutil if "cpu_thermal" is available, will fall back to `vcgencmd measure_temp` if not.
